version: "3.10"

services:
  web:
    build: 
    command: >
      sh -c "python manage.py migrate &&
             gunicorn book_api_project.wsgi:application --bind 0.0.0.0:8000 --workers 4". 
    ports:
      - "8000:8000"
    
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    
volumes:
  postgres_data: